import type {
  JobStatus,
  Customer,
  Vehicle,
  Mechanic,
  DVIItem,
  Part,
  Activity,
  JobCard,
  StatusConfig,
} from "@/types"

// Re-export types for backward compatibility
export type { JobStatus, Customer, Vehicle, Mechanic, DVIItem, Part, Activity, JobCard }

export const mechanics: Mechanic[] = [
  {
    id: "m1",
    name: "Ravi Kumar",
    avatar: "/indian-male-mechanic-portrait.jpg",
    specialty: "Engine Specialist",
    phone: "+91 98765 43210",
  },
  {
    id: "m2",
    name: "Suresh Patel",
    avatar: "/indian-male-auto-technician-portrait.jpg",
    specialty: "Electrical Systems",
    phone: "+91 98765 43211",
  },
  {
    id: "m3",
    name: "Amit Singh",
    avatar: "/indian-male-car-mechanic-portrait.jpg",
    specialty: "Brake & Suspension",
    phone: "+91 98765 43212",
  },
  {
    id: "m4",
    name: "Deepak Sharma",
    avatar: "/indian-male-auto-repair-technician-portrait.jpg",
    specialty: "General Repairs",
    phone: "+91 98765 43213",
  },
]

export const dviTemplates = [
  { id: "full", name: "Full Vehicle Inspection", itemCount: 42 },
  { id: "quick", name: "Quick Service Check", itemCount: 15 },
  { id: "brake", name: "Brake System Inspection", itemCount: 18 },
  { id: "ac", name: "A/C System Check", itemCount: 12 },
  { id: "pre-purchase", name: "Pre-Purchase Inspection", itemCount: 55 },
]

export const mockJobs: JobCard[] = [
  {
    id: "j1",
    jobNumber: "JOB-2024-001",
    customer: {
      id: "c1",
      name: "Rajesh Verma",
      phone: "+91 99887 76543",
      email: "rajesh.v@email.com",
      address: "42, MG Road, Bangalore",
    },
    vehicle: { id: "v1", make: "Toyota", model: "Camry", year: 2021, regNo: "KA 01 AB 1234", color: "Silver" },
    mechanic: mechanics[0],
    status: "working",
    dviPending: true,
    dviTemplate: "Full Vehicle Inspection",
    dviItems: [
      {
        id: "d1",
        category: "Brakes",
        name: "Front Brake Pads",
        status: "urgent",
        note: "Worn to 15%, needs immediate replacement",
      },
      {
        id: "d2",
        category: "Brakes",
        name: "Rear Brake Pads",
        status: "attention",
        note: "At 35%, replace within 5000km",
      },
      { id: "d3", category: "Brakes", name: "Brake Fluid Level", status: "good" },
      { id: "d4", category: "Engine", name: "Engine Oil Level", status: "good" },
      {
        id: "d5",
        category: "Engine",
        name: "Air Filter",
        status: "attention",
        note: "Slightly dirty, recommend replacement",
      },
      { id: "d6", category: "Tires", name: "Front Left Tire", status: "good" },
      { id: "d7", category: "Tires", name: "Front Right Tire", status: "pending" },
      { id: "d8", category: "Tires", name: "Rear Left Tire", status: "pending" },
      { id: "d9", category: "Tires", name: "Rear Right Tire", status: "pending" },
      { id: "d10", category: "Fluids", name: "Coolant Level", status: "good" },
    ],
    parts: [
      {
        id: "p1",
        name: "Front Brake Pads (Set)",
        partNumber: "TYT-BP-001",
        quantity: 1,
        unitPrice: 3500,
        laborCost: 800,
      },
      { id: "p2", name: "Air Filter", partNumber: "TYT-AF-042", quantity: 1, unitPrice: 850, laborCost: 200 },
    ],
    activities: [
      {
        id: "a1",
        timestamp: new Date("2024-01-15T09:00:00"),
        type: "status_change",
        description: "Job created and received",
        user: "Priya (Frontdesk)",
      },
      {
        id: "a2",
        timestamp: new Date("2024-01-15T09:30:00"),
        type: "status_change",
        description: "Assigned to Ravi Kumar",
        user: "Priya (Frontdesk)",
      },
      {
        id: "a3",
        timestamp: new Date("2024-01-15T10:15:00"),
        type: "status_change",
        description: "Status changed to Working",
        user: "Ravi Kumar",
      },
      {
        id: "a4",
        timestamp: new Date("2024-01-15T11:00:00"),
        type: "dvi_update",
        description: "DVI inspection started",
        user: "Ravi Kumar",
      },
    ],
    laborTotal: 1000,
    partsTotal: 4350,
    tax: 963,
    createdAt: new Date("2024-01-15T09:00:00"),
    updatedAt: new Date("2024-01-15T11:00:00"),
    estimatedCompletion: new Date("2024-01-15T16:00:00"),
    complaints: "Squeaking noise from front brakes, A/C not cooling properly",
  },
  {
    id: "j2",
    jobNumber: "JOB-2024-002",
    customer: { id: "c2", name: "Anita Sharma", phone: "+91 88776 65432", email: "anita.s@email.com" },
    vehicle: { id: "v2", make: "Honda", model: "City", year: 2020, regNo: "KA 02 CD 5678", color: "White" },
    mechanic: mechanics[1],
    status: "received",
    dviPending: false,
    dviTemplate: "Quick Service Check",
    dviItems: [],
    parts: [],
    activities: [
      {
        id: "a5",
        timestamp: new Date("2024-01-15T10:00:00"),
        type: "status_change",
        description: "Job created and received",
        user: "Priya (Frontdesk)",
      },
      {
        id: "a6",
        timestamp: new Date("2024-01-15T10:30:00"),
        type: "status_change",
        description: "Assigned to Suresh Patel",
        user: "Priya (Frontdesk)",
      },
    ],
    laborTotal: 0,
    partsTotal: 0,
    tax: 0,
    createdAt: new Date("2024-01-15T10:00:00"),
    updatedAt: new Date("2024-01-15T10:30:00"),
    complaints: "Regular service - Oil change and general checkup",
  },
  {
    id: "j3",
    jobNumber: "JOB-2024-003",
    customer: { id: "c3", name: "Mohammed Khan", phone: "+91 77665 54321", email: "mkhan@email.com" },
    vehicle: { id: "v3", make: "Maruti", model: "Swift", year: 2019, regNo: "KA 03 EF 9012", color: "Red" },
    status: "received",
    dviPending: true,
    dviItems: [],
    parts: [],
    activities: [
      {
        id: "a7",
        timestamp: new Date("2024-01-15T11:00:00"),
        type: "status_change",
        description: "Job created and received",
        user: "Priya (Frontdesk)",
      },
    ],
    laborTotal: 0,
    partsTotal: 0,
    tax: 0,
    createdAt: new Date("2024-01-15T11:00:00"),
    updatedAt: new Date("2024-01-15T11:00:00"),
    complaints: "Car not starting, battery seems weak",
  },
  {
    id: "j4",
    jobNumber: "JOB-2024-004",
    customer: { id: "c4", name: "Priya Nair", phone: "+91 66554 43210", email: "priya.n@email.com" },
    vehicle: { id: "v4", make: "Hyundai", model: "Creta", year: 2022, regNo: "KA 04 GH 3456", color: "Blue" },
    mechanic: mechanics[2],
    status: "ready",
    dviPending: false,
    dviTemplate: "Brake System Inspection",
    dviItems: [
      { id: "d11", category: "Brakes", name: "All Brake Components", status: "good", note: "Replaced and tested" },
    ],
    parts: [
      {
        id: "p3",
        name: "Rear Brake Pads (Set)",
        partNumber: "HYD-BP-002",
        quantity: 1,
        unitPrice: 2800,
        laborCost: 600,
      },
      { id: "p4", name: "Brake Disc (Rear)", partNumber: "HYD-BD-001", quantity: 2, unitPrice: 4500, laborCost: 1200 },
    ],
    activities: [
      {
        id: "a8",
        timestamp: new Date("2024-01-14T09:00:00"),
        type: "status_change",
        description: "Job created and received",
        user: "Priya (Frontdesk)",
      },
      {
        id: "a9",
        timestamp: new Date("2024-01-14T09:30:00"),
        type: "status_change",
        description: "Assigned to Amit Singh",
        user: "Priya (Frontdesk)",
      },
      {
        id: "a10",
        timestamp: new Date("2024-01-14T10:00:00"),
        type: "status_change",
        description: "Status changed to Working",
        user: "Amit Singh",
      },
      {
        id: "a11",
        timestamp: new Date("2024-01-15T09:00:00"),
        type: "status_change",
        description: "Status changed to Ready",
        user: "Amit Singh",
      },
      {
        id: "a12",
        timestamp: new Date("2024-01-15T09:30:00"),
        type: "estimate_sent",
        description: "Estimate sent via WhatsApp",
        user: "Priya (Frontdesk)",
      },
    ],
    laborTotal: 1800,
    partsTotal: 11800,
    tax: 2448,
    createdAt: new Date("2024-01-14T09:00:00"),
    updatedAt: new Date("2024-01-15T09:30:00"),
    complaints: "Grinding noise from rear wheels when braking",
  },
  {
    id: "j5",
    jobNumber: "JOB-2024-005",
    customer: { id: "c5", name: "Vikram Reddy", phone: "+91 55443 32109", email: "vikram.r@email.com" },
    vehicle: { id: "v5", make: "Tata", model: "Nexon", year: 2023, regNo: "KA 05 IJ 7890", color: "Green" },
    mechanic: mechanics[3],
    status: "completed",
    dviPending: false,
    dviTemplate: "Full Vehicle Inspection",
    dviItems: [
      { id: "d12", category: "General", name: "All Systems", status: "good", note: "Vehicle in excellent condition" },
    ],
    parts: [
      { id: "p5", name: "Engine Oil (5L)", partNumber: "GEN-OIL-5W30", quantity: 1, unitPrice: 2200, laborCost: 400 },
      { id: "p6", name: "Oil Filter", partNumber: "TATA-OF-001", quantity: 1, unitPrice: 450, laborCost: 0 },
    ],
    activities: [
      {
        id: "a13",
        timestamp: new Date("2024-01-13T09:00:00"),
        type: "status_change",
        description: "Job created and received",
        user: "Priya (Frontdesk)",
      },
      {
        id: "a14",
        timestamp: new Date("2024-01-13T14:00:00"),
        type: "status_change",
        description: "Status changed to Completed",
        user: "Deepak Sharma",
      },
      {
        id: "a15",
        timestamp: new Date("2024-01-13T15:00:00"),
        type: "payment",
        description: "Payment received - Cash ₹3,569",
        user: "Priya (Frontdesk)",
      },
    ],
    laborTotal: 400,
    partsTotal: 2650,
    tax: 549,
    createdAt: new Date("2024-01-13T09:00:00"),
    updatedAt: new Date("2024-01-13T15:00:00"),
    complaints: "Routine service and oil change",
  },
]

export const statusConfig: Record<JobStatus, StatusConfig> = {
  received: { label: "Received", color: "text-blue-400", bgColor: "bg-blue-500/20" },
  working: { label: "Working", color: "text-amber-400", bgColor: "bg-amber-500/20" },
  ready: { label: "Ready for Payment", color: "text-emerald-400", bgColor: "bg-emerald-500/20" },
  completed: { label: "Completed", color: "text-slate-400", bgColor: "bg-slate-500/20" },
}
