-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE tenant.activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  jobcard_id uuid NOT NULL,
  user_id uuid,
  activity_type text NOT NULL,
  description text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  entity_type text,
  entity_id uuid,
  ip_address inet,
  user_agent text,
  CONSTRAINT activities_pkey PRIMARY KEY (id),
  CONSTRAINT activities_jobcard_id_fkey FOREIGN KEY (jobcard_id) REFERENCES tenant.jobcards(id),
  CONSTRAINT activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES tenant.users(id)
);
CREATE TABLE tenant.customer_communications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  jobcard_id uuid,
  type text NOT NULL,
  direction text NOT NULL,
  subject text,
  message text,
  status text,
  metadata jsonb DEFAULT '{}'::jsonb,
  sent_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_communications_pkey PRIMARY KEY (id),
  CONSTRAINT customer_communications_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES tenant.customers(id),
  CONSTRAINT customer_communications_jobcard_id_fkey FOREIGN KEY (jobcard_id) REFERENCES tenant.jobcards(id),
  CONSTRAINT customer_communications_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES tenant.users(id)
);
CREATE TABLE tenant.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  phone text,
  email text,
  address text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenant.tenants(id)
);
CREATE TABLE tenant.dvi_checkpoint_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dvi_checkpoint_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE tenant.dvi_checkpoints (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  template_id uuid,
  category_id uuid,
  name text NOT NULL,
  description text,
  display_order integer DEFAULT 0,
  is_required boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dvi_checkpoints_pkey PRIMARY KEY (id),
  CONSTRAINT dvi_checkpoints_template_id_fkey FOREIGN KEY (template_id) REFERENCES tenant.dvi_templates(id),
  CONSTRAINT dvi_checkpoints_category_id_fkey FOREIGN KEY (category_id) REFERENCES tenant.dvi_checkpoint_categories(id)
);
CREATE TABLE tenant.dvi_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  jobcard_id uuid NOT NULL,
  checkpoint_id uuid NOT NULL,
  status text DEFAULT 'pending'::text,
  notes text,
  checkpoint_name text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dvi_items_pkey PRIMARY KEY (id),
  CONSTRAINT dvi_items_jobcard_id_fkey FOREIGN KEY (jobcard_id) REFERENCES tenant.jobcards(id)
);
CREATE TABLE tenant.dvi_photos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dvi_item_id uuid NOT NULL,
  storage_path text NOT NULL,
  url text NOT NULL,
  caption text,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dvi_photos_pkey PRIMARY KEY (id),
  CONSTRAINT dvi_photos_dvi_item_id_fkey FOREIGN KEY (dvi_item_id) REFERENCES tenant.dvi_items(id),
  CONSTRAINT dvi_photos_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES tenant.users(id)
);
CREATE TABLE tenant.dvi_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dvi_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE tenant.estimate_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  estimate_id uuid NOT NULL,
  part_id uuid,
  custom_name text,
  custom_part_number text,
  description text,
  qty integer NOT NULL,
  unit_price numeric NOT NULL,
  labor_cost numeric DEFAULT 0,
  total numeric DEFAULT (((qty)::numeric * unit_price) + labor_cost),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT estimate_items_pkey PRIMARY KEY (id),
  CONSTRAINT estimate_items_estimate_id_fkey FOREIGN KEY (estimate_id) REFERENCES tenant.estimates(id),
  CONSTRAINT estimate_items_part_id_fkey FOREIGN KEY (part_id) REFERENCES tenant.parts(id)
);
CREATE TABLE tenant.estimates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  jobcard_id uuid,
  created_by uuid,
  status text NOT NULL DEFAULT 'draft'::text,
  total_amount numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  currency text DEFAULT 'INR'::text,
  items jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  estimate_number text NOT NULL DEFAULT ''::text,
  customer_id uuid,
  vehicle_id uuid,
  description text,
  labor_total numeric DEFAULT 0,
  parts_total numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  valid_until timestamp with time zone,
  approved_at timestamp with time zone,
  rejected_at timestamp with time zone,
  rejection_reason text,
  CONSTRAINT estimates_pkey PRIMARY KEY (id),
  CONSTRAINT estimates_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenant.tenants(id),
  CONSTRAINT estimates_jobcard_id_fkey FOREIGN KEY (jobcard_id) REFERENCES tenant.jobcards(id),
  CONSTRAINT estimates_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES tenant.customers(id),
  CONSTRAINT estimates_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES tenant.vehicles(id)
);
CREATE TABLE tenant.inventory_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  part_id uuid NOT NULL,
  transaction_type text NOT NULL,
  quantity integer NOT NULL,
  unit_cost numeric,
  reference_type text,
  reference_id uuid,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_transactions_part_id_fkey FOREIGN KEY (part_id) REFERENCES tenant.parts(id),
  CONSTRAINT inventory_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES tenant.users(id)
);
CREATE TABLE tenant.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  jobcard_id uuid,
  estimate_id uuid,
  invoice_number text,
  status text NOT NULL DEFAULT 'pending'::text,
  subtotal numeric DEFAULT 0,
  tax numeric DEFAULT 0,
  total numeric DEFAULT 0,
  due_date date,
  issued_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  payment_mode text CHECK ((payment_mode = ANY (ARRAY['cash'::text, 'razorpay'::text])) OR payment_mode IS NULL),
  customer_id uuid,
  invoice_date timestamp with time zone DEFAULT now(),
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  paid_amount numeric DEFAULT 0,
  notes text,
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  balance numeric DEFAULT (total_amount - paid_amount),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenant.tenants(id),
  CONSTRAINT invoices_jobcard_id_fkey FOREIGN KEY (jobcard_id) REFERENCES tenant.jobcards(id),
  CONSTRAINT invoices_estimate_id_fkey FOREIGN KEY (estimate_id) REFERENCES tenant.estimates(id),
  CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES tenant.customers(id),
  CONSTRAINT invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES tenant.users(id)
);
CREATE TABLE tenant.jobcards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  job_number text NOT NULL,
  vehicle_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  created_by uuid,
  assigned_mechanic_id uuid,
  status text NOT NULL DEFAULT 'created'::text,
  details jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT jobcards_pkey PRIMARY KEY (id),
  CONSTRAINT jobcards_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenant.tenants(id),
  CONSTRAINT jobcards_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES tenant.vehicles(id),
  CONSTRAINT jobcards_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES tenant.customers(id),
  CONSTRAINT jobcards_assigned_mechanic_id_fkey FOREIGN KEY (assigned_mechanic_id) REFERENCES tenant.mechanics(id)
);
CREATE TABLE tenant.mechanics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  phone text,
  email text,
  skills ARRAY,
  hourly_rate numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT mechanics_pkey PRIMARY KEY (id),
  CONSTRAINT mechanics_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenant.tenants(id)
);
CREATE TABLE tenant.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  customer_id uuid,
  jobcard_id uuid,
  channel text NOT NULL,
  template text,
  payload jsonb,
  status text DEFAULT 'queued'::text,
  sent_at timestamp with time zone,
  user_id uuid,
  category text,
  entity_type text,
  entity_id uuid,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenant.tenants(id),
  CONSTRAINT notifications_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES tenant.customers(id),
  CONSTRAINT notifications_jobcard_id_fkey FOREIGN KEY (jobcard_id) REFERENCES tenant.jobcards(id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES tenant.users(id)
);
CREATE TABLE tenant.part_usages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  jobcard_id uuid NOT NULL,
  part_id uuid NOT NULL,
  qty integer NOT NULL,
  unit_price numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT part_usages_pkey PRIMARY KEY (id),
  CONSTRAINT part_usages_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenant.tenants(id),
  CONSTRAINT part_usages_jobcard_id_fkey FOREIGN KEY (jobcard_id) REFERENCES tenant.jobcards(id),
  CONSTRAINT part_usages_part_id_fkey FOREIGN KEY (part_id) REFERENCES tenant.parts(id)
);
CREATE TABLE tenant.parts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  sku text,
  name text NOT NULL,
  description text,
  unit_cost numeric DEFAULT 0,
  sell_price numeric DEFAULT 0,
  stock_on_hand integer DEFAULT 0,
  reorder_level integer DEFAULT 0,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT parts_pkey PRIMARY KEY (id),
  CONSTRAINT parts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenant.tenants(id)
);
CREATE TABLE tenant.payment_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  invoice_id uuid NOT NULL,
  mode text NOT NULL CHECK (mode = ANY (ARRAY['cash'::text, 'razorpay'::text])),
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  razorpay_order_id text,
  razorpay_payment_id text,
  razorpay_signature text,
  status text NOT NULL DEFAULT 'initiated'::text CHECK (status = ANY (ARRAY['initiated'::text, 'success'::text, 'failed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  paid_at timestamp with time zone,
  CONSTRAINT payment_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT payment_transactions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenant.tenants(id),
  CONSTRAINT payment_transactions_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES tenant.invoices(id)
);
CREATE TABLE tenant.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  invoice_id uuid NOT NULL,
  amount numeric NOT NULL,
  method text,
  gateway_ref text,
  status text NOT NULL DEFAULT 'initiated'::text,
  paid_at timestamp with time zone,
  payment_date timestamp with time zone DEFAULT now(),
  payment_method text NOT NULL DEFAULT 'cash'::text,
  reference_number text,
  notes text,
  received_by uuid,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenant.tenants(id),
  CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES tenant.invoices(id),
  CONSTRAINT payments_received_by_fkey FOREIGN KEY (received_by) REFERENCES tenant.users(id)
);
CREATE TABLE tenant.razorpay_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL UNIQUE,
  key_id text NOT NULL,
  key_secret text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT razorpay_settings_pkey PRIMARY KEY (id),
  CONSTRAINT razorpay_settings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenant.tenants(id)
);
CREATE TABLE tenant.settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL UNIQUE,
  tax_rate numeric DEFAULT 0,
  currency text DEFAULT 'INR'::text,
  timezone text DEFAULT 'Asia/Kolkata'::text,
  sms_enabled boolean DEFAULT false,
  email_enabled boolean DEFAULT false,
  whatsapp_enabled boolean DEFAULT false,
  invoice_prefix text DEFAULT 'INV-'::text,
  job_prefix text DEFAULT 'JOB-'::text,
  estimate_prefix text DEFAULT 'EST-'::text,
  invoice_footer text,
  logo_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT settings_pkey PRIMARY KEY (id)
);
CREATE TABLE tenant.tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE tenant.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  auth_user_id uuid NOT NULL,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  role text DEFAULT 'frontdesk'::text,
  avatar_url text,
  is_active boolean DEFAULT true,
  last_login timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenant.tenants(id),
  CONSTRAINT users_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE tenant.vehicles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  reg_no text NOT NULL,
  vin text,
  make_id uuid,
  model_id uuid,
  year smallint,
  odometer integer,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vehicles_pkey PRIMARY KEY (id),
  CONSTRAINT vehicles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenant.tenants(id),
  CONSTRAINT vehicles_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES tenant.customers(id),
  CONSTRAINT vehicles_make_id_fkey FOREIGN KEY (make_id) REFERENCES public.vehicle_make(id),
  CONSTRAINT vehicles_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.vehicle_model(id)
);